# Build only on tags that look like v*
workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
    - when: never

stages: [build]

variables:
  REGISTRY: registry.benac.dev
  IMAGE_NAME: cipherlot-node
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:v1.23.0-debug
  CONTEXT_DIR: cipherlot-node
  DOCKERFILE: cipherlot-node/Dockerfile

build-image:
  stage: build
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  before_script:
    # Copy CA certificate from GitLab runner's trust store
    - mkdir -p /kaniko/ssl/certs
    - cp /etc/ssl/certs/ca-certificates.crt /kaniko/ssl/certs/
    # If Centroid CA is available on runner, append it
    - |
      if [ -f /etc/ssl/centroid-ca/certs/ca-root.crt ]; then
        cat /etc/ssl/centroid-ca/certs/ca-root.crt >> /kaniko/ssl/certs/ca-certificates.crt
      fi
  script:
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/$CONTEXT_DIR" \
        --dockerfile "$CI_PROJECT_DIR/$DOCKERFILE" \
        --destination "$REGISTRY/$IMAGE_NAME:$CI_COMMIT_TAG" \
        --destination "$REGISTRY/$IMAGE_NAME:latest" \
        --cache=true \
        --build-arg VERSION=$CI_COMMIT_TAG \
        --registry-certificate=$REGISTRY=/kaniko/ssl/certs/ca-certificates.crt