apiVersion: v1
kind: Namespace
metadata:
  name: cipherlot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cipherlot-node
  namespace: cipherlot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cipherlot-node
  template:
    metadata:
      labels:
        app: cipherlot-node
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: node
        image: cipherlot-node:v0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DATA_ROOT
          value: /data
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cipherlot-node
  namespace: cipherlot
spec:
  type: NodePort
  selector:
    app: cipherlot-node
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: 30999
