apiVersion: v1
kind: Service
metadata:
  name: cipherlot-node-agent
  namespace: cipherlot
spec:
  type: NodePort
  selector:
    app: cipherlot-node-agent
  internalTrafficPolicy: Local
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30999